messenger/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('new_message/', views.new_message, name='new_message'),
    path('<str:username>/', views.get_user_messages, name='user-page'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('messenger.urls')),
    path('admin/', admin.site.urls),
]

messenger/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Message(models.Model):
  user = models.ForeignKey(
    to=User,
    on_delete=models.DO_NOTHING,
    related_name='user_to',
  )
  author = models.ForeignKey(
    to=User,
    on_delete=models.DO_NOTHING,
    related_name='msg_author',
  )
  text = models.CharField(
    max_length=500,
  )
  pub_date = models.DateTimeField(
    auto_now_add=True,
  )

  def __str__(self):
    return f"{self.author.username} -> {self.user.username}: {self.text}"

messenger/forms.py
from django import forms

from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('author',)

messenger/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model

from .forms import MessageForm
from .models import Message


User = get_user_model()


def index(request):
    if not request.user.is_authenticated:
      return render(request, 'auth.html')
    incoming_msgs = Message.objects.filter(user=request.user)
    outgoing_msgs = Message.objects.filter(author=request.user)
    messages = [*outgoing_msgs, *incoming_msgs]
    
    result = set(msg.author for msg in messages)
    return render(
        request,
        'index.html',
        {
            'form': MessageForm(),
            'messages': result,
        }
    )


def get_user_messages(request, username):
    author = get_object_or_404(User, username=username)
    outgoing_msgs = Message.objects.filter(
        author=author,
        user=request.user,
    )
    incoming_msgs = Message.objects.filter(
        author=request.user,
        user=author,
    )
    messages = sorted(
        [*outgoing_msgs, *incoming_msgs],
        key=lambda msg: msg.pub_date
    )

    return render(
        request,
        'messages.html',
        {
            'messages': messages,
            'author': author,
        }
    )


def new_message(request):
    if request.method != 'POST':
        return redirect('index')
    form = MessageForm(request.POST)
    if form.is_valid():
        message = form.save(commit=False)
        message.author = request.user
        message.save()

    return redirect('user-page', username=form.cleaned_data['user'])

templates/auth.html
Авторизируйтесь
<a href="/admin">log in</a>

templates/index.html
<p><b>Кому напишем?</b></p>
<form action="{% url 'new_message' %}" method="POST">
    {% csrf_token %}
    {{ form.as_ul }}
    <p><input type="submit"></p>
</form>
Диалоги
{% for msg_user in messages %}
    <br>
    <a href="{% url 'user-page' msg_user.username %}">
        {{ msg_user.username }}
    </a>
{% endfor %}

templates/messages.html
{% for msg in messages %}
    {% ifchanged msg.pub_date.date %}{{ msg.pub_date.date }}<br>{% endifchanged %}
    {% ifchanged msg.author %}
        <b>{{ msg.author }} {{ msg.pub_date.time }}</b><br>
    {% endifchanged %}
    {{ msg.text }}
    <br>
{% endfor %}
<form action="{% url 'new_message' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="user" maxlength="500" required="" id="id_user" value={{ author.pk }}>
    <input type="text" name="text" maxlength="500" required="" id="id_text">
    <input type="submit"></input>
</form>
<br>
<br>
<br>
<a href="{% url 'index' %}">На главную</a>